"""add_celery_task_id_full_pipeline_jobtype

Revision ID: 35da57b15eac
Revises: c3934c18e36c
Create Date: 2026-04-30 10:25:24.284103
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35da57b15eac'
down_revision: Union[str, None] = 'c3934c18e36c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('render_jobs', sa.Column('celery_task_id', sa.String(length=36), nullable=True))
    op.add_column('render_jobs', sa.Column('job_type_detail', sa.String(length=200), nullable=True))
    op.create_index(op.f('ix_render_jobs_celery_task_id'), 'render_jobs', ['celery_task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_render_jobs_celery_task_id'), table_name='render_jobs')
    op.drop_column('render_jobs', 'job_type_detail')
    op.drop_column('render_jobs', 'celery_task_id')
    # ### end Alembic commands ###
