"""add_camera_angle

Revision ID: 552670812883
Revises: cc753d6150ab
Create Date: 2026-05-01 14:34:52.560850
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '552670812883'
down_revision: Union[str, None] = 'cc753d6150ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scene_prompts', sa.Column('camera_angle', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scene_prompts', 'camera_angle')
    # ### end Alembic commands ###
