"""add_image_pregen_columns

Revision ID: c3934c18e36c
Revises: 001
Create Date: 2026-04-30 09:38:40.998546
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c3934c18e36c'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assets', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('audio_plans_project_id_key', 'audio_plans', type_='unique')
    op.drop_index('ix_audio_plans_project_id', table_name='audio_plans')
    op.create_index(op.f('ix_audio_plans_project_id'), 'audio_plans', ['project_id'], unique=True)
    op.add_column('characters', sa.Column('reference_image_path', sa.String(length=1000), nullable=True))
    op.add_column('locations', sa.Column('reference_image_path', sa.String(length=1000), nullable=True))
    op.alter_column('projects', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('projects', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('render_jobs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('render_jobs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('scene_prompts_scene_id_key', 'scene_prompts', type_='unique')
    op.drop_index('ix_scene_prompts_scene_id', table_name='scene_prompts')
    op.create_index(op.f('ix_scene_prompts_scene_id'), 'scene_prompts', ['scene_id'], unique=True)
    op.add_column('scenes', sa.Column('scene_ref_image_path', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scenes', 'scene_ref_image_path')
    op.drop_index(op.f('ix_scene_prompts_scene_id'), table_name='scene_prompts')
    op.create_index('ix_scene_prompts_scene_id', 'scene_prompts', ['scene_id'], unique=False)
    op.create_unique_constraint('scene_prompts_scene_id_key', 'scene_prompts', ['scene_id'])
    op.alter_column('render_jobs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('render_jobs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('projects', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('projects', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('locations', 'reference_image_path')
    op.drop_column('characters', 'reference_image_path')
    op.drop_index(op.f('ix_audio_plans_project_id'), table_name='audio_plans')
    op.create_index('ix_audio_plans_project_id', 'audio_plans', ['project_id'], unique=False)
    op.create_unique_constraint('audio_plans_project_id_key', 'audio_plans', ['project_id'])
    op.alter_column('assets', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
