"""add_scene_breakdown_camera_angle

Revision ID: cc753d6150ab
Revises: 35da57b15eac
Create Date: 2026-05-01 14:33:13.266552
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc753d6150ab'
down_revision: Union[str, None] = '35da57b15eac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scene_prompts', sa.Column('scene_breakdown', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scene_prompts', 'scene_breakdown')
    # ### end Alembic commands ###
