#!/usr/bin/env bash
# Submit 9 mini-films: 3 Adiyogi follow-ups, 3 simplistic Krishna, 3 Saint Dnyaneshwar.
# All Wan22 pipeline, drains FIFO via queue scanner.
set -euo pipefail
BACKEND="${BACKEND_URL:-http://localhost:8002}"

post() {
    local title="$1" story="$2" dur="$3"
    local resp id
    resp=$(curl -sf -X POST "$BACKEND/api/projects" -H "Content-Type: application/json" \
        -d "$(python3 -c "import json,sys; print(json.dumps({
            'title': '$title',
            'original_story_text': sys.stdin.read(),
            'total_target_duration_seconds': $dur,
            'pipeline_profile': 'wan22_text_only',
        }))" <<< "$story")")
    id=$(python3 -c "import json,sys; print(json.loads(sys.stdin.read())['id'])" <<< "$resp")
    echo "  $title -> $id"
}

echo "=== Submitting 9 mythology mini-films (Wan22) ==="

# ── Adiyogi follow-ups ─────────────────────────────────────────────────────
post "ad_12_adiyogi_saptarishis" "A 30-second mini-film. Adiyogi — Shiva in his splendid human form, tall bronze-skinned male, long matted jata locks, three horizontal bands of sacred ash (vibhuti) on forehead and chest, closed third eye, crescent moon in hair, snake (Vasuki) at neck, rudraksha mala, tiger-skin loincloth — transmits the yogic sciences to the Saptarishis (Seven Sages) at Kanti Sarovar above Kedarnath. Seven seated sages — bearded, in plain ochre dhotis, hair tied in knots, deeply attentive faces — sit in a semicircle on the snow-dusted shore of a glacial lake at sunrise. Scene 1 (6s, wide establishing): Kanti Sarovar at dawn — frozen alpine lake mirroring the surrounding peaks, prayer flags, mist. The seven sages already seated in semicircle. Camera 60-80 ft, slow push-in. Mood: ancient, sacred. Scene 2 (6s, mid arrival): Adiyogi sits cross-legged on a flat boulder facing them, back perfectly straight, eyes half-open in a meditative gaze, hands in chin mudra resting on his knees. Camera 25-30 ft, three-quarter. Mood: presence, transmission. Scene 3 (6s, sage close-up): Tight close-up of one of the sages — eyes closed, single tear running down cheek, expression of receiving knowledge. Faint golden light on his face. Camera 4 ft, shallow depth-of-field. Mood: revelation. Scene 4 (6s, transmission wide): Subtle golden light arcs from Adiyogi's brow toward the sages' brows. The lake surface ripples once. Snowflakes drift. Camera 20-30 ft, side angle. Mood: cosmic. Scene 5 (6s, final): All seven sages bow forward in pranam, foreheads to the cold stone. Adiyogi remains seated, eyes now fully open, gaze on the rising sun. Camera 30-40 ft, low angle. Mood: completion, lineage born. Consistency: SAME Adiyogi figure and SAME seven sages across scenes; SAME Kanti Sarovar setting; cold blue-gold palette." 30

post "ad_13_adiyogi_ganga" "A 24-second mini-film. Adiyogi — Shiva in human form, tall bronze-skinned, long matted jata locks tied loosely on top of his head, sacred ash bands on forehead and chest, closed third eye, crescent moon in hair, snake at neck, rudraksha mala, tiger-skin loincloth — receives the descending river Ganga into his matted locks to spare the earth from her thunderous fall. Setting: a high Himalayan ridge at dusk, sky deep indigo with first stars, snowy peaks behind. Scene 1 (6s, wide setup): Adiyogi stands tall on a granite outcrop, arms slightly out, head tilted upward, looking at the sky. Below him, the curve of the earth visible. Camera 50-60 ft, low angle. Mood: anticipation. Scene 2 (6s, descent wide): A massive cascading column of luminous turquoise water descends from the upper sky toward his head, spiraling, slowed by the air around him. Camera 40 ft, wide. Mood: cosmic, monumental. Scene 3 (6s, impact close): Tight close-up of his head and matted locks as the column of water enters and is absorbed into the strands, foaming and roiling within the jata. Spray, mist, golden particles. Camera 6 ft. Mood: containment, divinity. Scene 4 (6s, release wide): A single gentle stream of glowing water emerges from one strand of his hair and flows down the rock to begin its earthly journey as a river. Adiyogi unchanged, calm, looking down at the new stream. Camera 25-30 ft, side angle. Mood: birth of a river, mercy. Consistency: SAME Adiyogi figure across all four scenes; SAME Himalayan ridge setting; cool indigo/turquoise/gold palette." 24

post "ad_14_adiyogi_nataraja" "An 18-second mini-film. Adiyogi — Shiva — in the cosmic dance form of Nataraja: tall bronze figure, four arms (upper-right holding a damaru drum, upper-left holding a small flame, lower-right in abhaya mudra fearless gesture, lower-left pointing across body to the raised foot), right foot pressing down a small demon figure (Apasmara) symbolizing ignorance, left leg lifted across the body, surrounded by a ring of cosmic fire. Matted jata flying outward, snake at neck, crescent moon, third eye glowing, anklets, dhoti. Setting: an empty primordial void — black background dusted with stars, a circular halo of orange-gold flame surrounding him. Scene 1 (6s, mid wide): Adiyogi mid-dance, frozen in the iconic Nataraja pose, flame ring slowly rotating around him. Camera 15-20 ft, frontal. Mood: cosmic, eternal. Scene 2 (6s, close drum): Tight close-up of the upper-right hand spinning the damaru drum — small drum twirling, two beads striking each side, sound waves visible as faint blue ripples. Camera 3 ft. Mood: rhythm of creation. Scene 3 (6s, full body rotating): Slow orbit around the full Nataraja figure, flame ring rotating, his pose unchanging, sparks drifting off into the cosmic void. Camera 20 ft, slow rotation. Mood: eternal dance. Consistency: SAME pose across all three scenes (do not change limb positions); SAME flame ring; black-cosmic-with-orange-gold palette." 18

# ── Krishna (simplistic) ───────────────────────────────────────────────────
post "ad_15_krishna_flute" "A 12-second simple mini-film. Young Krishna — a beautiful boy of about 12, blue-tinted skin, long dark curly hair, peacock feather tucked behind one ear, yellow silk dhoti tied at the waist, simple gold jewelry, holding a wooden bansuri (flute) — plays his flute at the edge of the Yamuna river at golden hour. Setting: Vrindavan riverbank, soft amber light, river water glowing, a few peacocks nearby, gentle reeds. Scene 1 (6s, mid close): Krishna stands cross-legged leaning against a tree, brings the flute to his lips, begins to play. Soft smile, eyes closed. Camera 6-8 ft, three-quarter angle, soft golden rim light. Mood: peace, devotion. Scene 2 (6s, response wide): Pulled-back shot — two peacocks fan their tails in response, a calf turns its head toward him, the river ripples gently. Krishna still playing in the corner of the frame. Camera 20-25 ft, wide. Mood: enchantment, harmony. Consistency: SAME Krishna figure both scenes; SAME Vrindavan riverbank; warm-gold palette." 12

post "ad_16_krishna_butter" "A 12-second simple mini-film. Young Krishna as a small toddler of about 4 — chubby blue-tinted child, large bright eyes, curly hair with one peacock feather, tiny yellow dhoti, anklets, soft baby cheeks — sneaks butter from a clay pot in a humble Vrindavan kitchen. Setting: warm clay-walled village kitchen, terracotta pots, a low wooden stool, soft window light. Scene 1 (6s, action close): Krishna stands on his tiptoes on a wooden stool, reaches both hands into a clay pot of fresh white butter (makhan), grins mischievously as he scoops out a handful, smears some on his cheek. Camera 4-5 ft, three-quarter. Mood: playful, adorable. Scene 2 (6s, caught wide): His mother Yashoda enters from the doorway — gentle woman in a simple sari, surprised then smiling expression. Krishna looks at her with butter-covered fingers, frozen in the act, eyes wide and innocent. Camera 12-15 ft, wide. Mood: love, mischief, warmth. Consistency: SAME toddler Krishna both scenes; SAME kitchen; warm golden-brown palette." 12

post "ad_17_krishna_cows" "A 12-second simple mini-film. Young Krishna — a beautiful boy of about 12, blue-tinted skin, long dark curly hair, peacock feather behind one ear, yellow silk dhoti, simple gold jewelry, a long shepherd's stick — leads a herd of cows through the meadows of Vrindavan at sunset. Setting: open green meadow, low golden sun, scattered banyan trees, a small group of brown-and-white cows with calves. Scene 1 (6s, wide tracking): Krishna walks barefoot through the meadow with a small herd of about 8 cows following him. He turns once and looks at a calf trailing behind, smiles. Camera 25-30 ft, slow tracking. Mood: pastoral, joyful, golden. Scene 2 (6s, close moment): Tight medium shot — Krishna kneels beside the trailing calf and gently strokes its head. The calf nuzzles his hand. Soft sunset rim light. Camera 5-6 ft. Mood: tender, divine simplicity. Consistency: SAME Krishna figure both scenes; SAME meadow; warm golden-green palette." 12

# ── Saint Dnyaneshwar ──────────────────────────────────────────────────────
post "ad_18_dnyaneshwar_newasa" "A 30-second mini-film. Saint Dnyaneshwar — a young Marathi saint-poet of about 15, slim youthful frame, gentle radiant face, long dark hair tied loosely, simple ochre dhoti and shawl, rudraksha mala, calm luminous eyes — dictates the Dnyaneshwari (his Marathi commentary on the Bhagavad Gita) at Newasa, Maharashtra, in the year 1290 CE. Setting: a large gnarled banyan tree at the edge of a quiet village, late-afternoon golden light, a small group of scribes seated in a semicircle taking down his words on palm-leaf manuscripts with iron styluses. Scene 1 (6s, wide establishing): The banyan tree with its aerial roots, a stone platform beneath, Dnyaneshwar seated on the platform, six scribes around him in a half-circle. Indian village backdrop. Camera 30-40 ft, slow push-in. Mood: serene scholarship. Scene 2 (6s, dictation mid): Dnyaneshwar speaks gently with one hand raised in a teaching gesture, eyes half-closed, lips moving softly. Camera 8-10 ft, three-quarter. Mood: inspired transmission. Scene 3 (6s, scribe close): Tight close-up of an older scribe's hands — wrinkled fingers gripping an iron stylus, etching Marathi script onto a long narrow palm-leaf. Inkwell beside him. Camera 2-3 ft, macro feel. Mood: preservation, devotion. Scene 4 (6s, listener faces): Slow pan across the faces of three scribes — each one rapt, eyes shining, one with a single tear, expressions of receiving sacred knowledge. Camera 5 ft, side dolly. Mood: reverence. Scene 5 (6s, final wide): Dnyaneshwar finishes speaking, lowers his hand, smiles gently. The scribes bow their heads. Golden hour light filters through banyan leaves above them. Camera 20-30 ft, wide. Mood: completion, legacy. Consistency: SAME Dnyaneshwar figure across all five scenes; SAME banyan tree and stone platform setting; same six scribes; warm amber-green palette." 30

post "ad_19_dnyaneshwar_buffalo" "A 24-second mini-film depicting the famous miracle of Saint Dnyaneshwar making a buffalo recite the Vedas. Saint Dnyaneshwar — a young saint-poet of about 14, slim radiant frame, gentle face, long dark hair tied loosely, simple ochre dhoti and shawl, rudraksha mala, calm eyes — stands at the edge of a Maharashtrian village street where a group of orthodox brahmin priests in white dhotis with shaved heads have been mocking him and his siblings. A large dark water-buffalo stands placidly nearby chewing grass. Scene 1 (6s, confrontation wide): The brahmins gesturing dismissively at Dnyaneshwar and his siblings (a girl and two boys, all young, in simple clothing). The buffalo in the background. Village backdrop. Camera 20-25 ft, wide. Mood: tension. Scene 2 (6s, decision mid): Dnyaneshwar's face — calm and unprovoked. He turns slowly and walks toward the buffalo, gently placing his right hand on its forehead. Camera 8 ft, three-quarter. Mood: quiet conviction. Scene 3 (6s, miracle close): Tight close-up of the buffalo's face — large dark eyes blink, then its mouth opens and clear Sanskrit verses emanate (visualize as faint golden light around its mouth, sound waves). Dnyaneshwar's hand still on its forehead. Camera 3 ft. Mood: wonder. Scene 4 (6s, awe wide): The brahmins fall to their knees, hands joined in pranam, expressions of shock and humility. Dnyaneshwar lowers his hand and steps back, calm and unchanged. The buffalo silent again, chewing grass. Camera 20-25 ft, wide. Mood: humility, divine demonstration. Consistency: SAME Dnyaneshwar figure across all four scenes; SAME buffalo; SAME village street; warm earth-tone palette." 24

post "ad_20_dnyaneshwar_samadhi" "A 24-second mini-film of Saint Dnyaneshwar entering Sanjeevan Samadhi (voluntary living entombment) at Alandi at age 21 in 1296 CE. Dnyaneshwar — slim radiant young saint, gentle luminous face, long dark hair, simple ochre dhoti and shawl, rudraksha mala — descends into an underground stone chamber to enter a state of conscious eternal meditation. Setting: the Alandi sacred ground beside the Indrayani river, devotees and his siblings gathered around a small stone-lined underground chamber with a square opening at ground level. Soft early-morning light, marigold petals scattered. Scene 1 (6s, gathering wide): A small gathered crowd in respectful silence — including his three siblings (Nivritti, Sopan, Muktabai) standing nearest the chamber opening. Dnyaneshwar stands at the edge of the opening, calm and ready. Camera 25-30 ft, wide. Mood: solemn, sacred. Scene 2 (6s, farewell close): Tight close-up of Dnyaneshwar's face — peaceful smile, eyes shining, looking once at his siblings. His sister Muktabai's face beside him with a single tear but accepting. Camera 4-5 ft. Mood: tender farewell, acceptance. Scene 3 (6s, descent mid): Dnyaneshwar lowers himself gracefully into the underground stone chamber, seats himself cross-legged in padmasana, hands resting on knees in chin mudra, eyes closed. The chamber stone visible around him. Camera 8-10 ft, looking down into the chamber. Mood: surrender, eternity. Scene 4 (6s, sealing wide): A large flat stone slab is gently lowered over the opening by the devotees, sealing the chamber. Marigold petals scattered on top. The siblings bow. Soft golden light. Camera 15-20 ft, wide. Mood: completion, eternal presence. Consistency: SAME Dnyaneshwar figure across all four scenes; SAME chamber and Alandi setting; same siblings; warm gold-ochre palette." 24

# ── Lifestyle / product simple ads ────────────────────────────────────────
post "ad_21_coffee_pour_drink" "A 12-second simple lifestyle ad. A man in his 30s, clean-shaven, dark hair, wearing a soft cream knit sweater, sits at a sunlit wooden kitchen counter pouring and drinking fresh coffee. Setting: bright minimal kitchen, large window with morning light, white walls, plain ceramic mug, glass carafe of black coffee. Scene 1 (6s, pour close): Tight close-up of his hand tilting the glass carafe and pouring a steady stream of dark coffee into a plain white ceramic mug. Steam rising. Camera 2-3 ft, shallow depth-of-field. Mood: ritual, calm. Scene 2 (6s, drink mid): Pulled-back shot — he lifts the mug with both hands, takes a slow first sip with eyes closed briefly, then opens them and smiles softly looking out the window. Camera 6-8 ft, three-quarter. Mood: morning satisfaction. Consistency: SAME man both scenes, SAME mug, SAME kitchen, warm morning light." 12

post "ad_22_cola_drink" "A 12-second simple lifestyle ad. A young woman in her mid-20s, casual summer t-shirt and jeans, hair in a loose ponytail, sits on a sun-drenched outdoor cafe terrace drinking a cold cola. Setting: sunny outdoor cafe, wooden table, cold glass bottle of cola beaded with condensation, a tall glass with ice, lemon slice on the rim, leafy plants in background. Scene 1 (6s, pour close): Tight close-up of cola being poured from the cold glass bottle into a tall glass over ice — the dark fizzing liquid cascading, bubbles rising, condensation glittering. Camera 2-3 ft, shallow depth-of-field. Mood: refreshing, vibrant. Scene 2 (6s, sip mid): Pulled-back shot — she lifts the glass, takes a long satisfied sip, lowers it with a small smile, looking off-camera. Sunshine on her face. Camera 6-8 ft, three-quarter. Mood: summer pleasure. Consistency: SAME woman both scenes, SAME glass, SAME terrace, bright warm summer light." 12

post "ad_23_birkin_bag_modeling" "A 12-second simple luxury fashion ad. A tall slim woman in her late 20s, elegant face with sharp cheekbones, long dark hair pulled back in a low chignon, wearing a tailored cream silk blouse, fitted high-waisted black trousers, low pointed heels, neutral makeup — modeling an iconic structured Hermes Birkin handbag in tan-brown saddle leather with gold hardware. Setting: a minimal high-end studio with a soft neutral grey gradient backdrop, clean polished floor, single soft key light from the side. Scene 1 (6s, walk wide): She walks slowly toward the camera carrying the Birkin bag in her right hand at her side, confident neutral expression. Camera 15-20 ft, frontal, slow dolly back. Mood: refined elegance. Scene 2 (6s, pose mid): She stops, turns slightly to a three-quarter pose, raises the Birkin slightly to display it at hip level — the bag in clear focus showing its structured shape, top handles, padlock and clochette. She holds a still posed expression looking off-camera. Camera 6-8 ft, three-quarter. Mood: luxury, poise. Consistency: SAME model both scenes, SAME Birkin bag, SAME studio backdrop, soft neutral palette." 12

echo ""
echo "=== All 12 submitted (9 mythology + 3 lifestyle) ==="
echo "Total now in queue: project list at $BACKEND/api/projects"
