#!/usr/bin/env bash
# Submit 12 single-story 60s mini-series from Indian history + mythology
# through the Wan22 pipeline. Each project = one coherent narrative with
# 2-3 named characters. Beats are written as single-character shots so
# the one-character-per-scene rule maps cleanly.
set -euo pipefail
BACKEND="${BACKEND_URL:-http://localhost:8002}"

post() {
    local title="$1" story="$2" dur="$3"
    local resp
    resp=$(curl -sf -X POST "$BACKEND/api/projects" -H "Content-Type: application/json" \
        -d "$(python3 -c "import json,sys; print(json.dumps({
            'title': '$title',
            'original_story_text': sys.stdin.read(),
            'total_target_duration_seconds': $dur,
            'pipeline_profile': 'wan22_text_only',
        }))" <<< "$story")")
    local id
    id=$(python3 -c "import json,sys; print(json.loads(sys.stdin.read())['id'])" <<< "$resp")
    echo "  $title -> $id"
}

echo "=== Submitting 12 historical/mythological mini-series (Wan22) ==="

post "hist_01_krishna_gita_arjuna" "A 60-second mini-series from the Mahabharata: the moment Krishna preaches the Bhagavad Gita to Arjuna on the battlefield of Kurukshetra. Two characters: Arjuna, a tall warrior in golden armor with long dark hair tied back, a Gandiva bow in hand, anguished; and Krishna, his charioteer with blue-tinted skin, peacock feather in crown, yellow silk robes, serene divine smile. Beats (single character per beat): wide shot of two massive armies facing each other across a dusty plain at dawn, closeup of Arjuna's anguished face seeing his cousins and gurus in the opposing army, Arjuna's bow slipping from his hand into the dust, closeup of Krishna turning toward him from the chariot reins with calm eyes, Krishna's hand raised in teaching mudra, Arjuna kneeling on the chariot floor head bowed listening, Krishna's face haloed in soft divine light explaining duty, a brief cosmic-form vision (Krishna's Vishvarupa silhouette against starfield), Arjuna's eyes widening with awe, Arjuna rising with renewed resolve and lifting his bow, closeup of Krishna's gentle approving smile, Arjuna blowing his conch as the chariot wheels begin to roll. Camera mix of wide battlefield and intimate two-shot framings. Warm dawn light, dust haze, banners snapping. Mood: profound, transcendent, mythic." 60

post "hist_02_buddha_sujata_kheer" "A 60-second mini-series: the moment young Sujata offers a bowl of kheer (rice pudding) to the emaciated Siddhartha beneath the Bodhi tree at Bodh Gaya, ending his extreme asceticism. Two characters: Siddhartha (pre-enlightenment Buddha), gaunt, dark skin from years of fasting, ribs visible, sitting cross-legged under a peepal tree, eyes closed; and Sujata, a young village woman in a simple cream-colored sari, gold bangles, carrying a golden bowl. Beats: Sujata walking barefoot through a forest path at dawn carrying the bowl, closeup of the steaming kheer in the polished bowl, Sujata bowing as she sees the meditator (single shot of her bowing), Siddhartha's emaciated face with eyes slowly opening, Sujata kneeling and offering the bowl with both hands, closeup of Siddhartha's thin hands accepting it, Siddhartha lifting the bowl to his lips, his hollow cheeks visibly filling with color, light streaming through Bodhi leaves illuminating his face, his eyes opening fully with peace, Sujata's reverent smile, Siddhartha's first faint smile of awakening, a single Bodhi leaf falling to the ground. Camera 3-10 feet, soft golden dawn light, leaf-dappled. Mood: tender, fragile, awakening." 60

post "hist_03_chanakya_chandragupta_forest" "A 60-second mini-series: the old strategist Chanakya teaches the young Chandragupta Maurya the art of statecraft in a forest hermitage, plotting the overthrow of the Nanda dynasty. Two characters: Chanakya, an old Brahmin with shaved head and long white beard, simple white dhoti, wooden staff, sharp piercing eyes; and Chandragupta, a teenage boy with strong jaw, simple loincloth, calloused hands, intent gaze. Beats: wide shot of a forest hermitage at dusk with a fire pit, Chanakya tracing a map of Magadha in the dust with his staff (closeup of staff and dust map), Chandragupta crouched watching the map, Chanakya pointing into the distance toward an imagined fort, Chandragupta sharpening a wooden practice sword on a stone, Chanakya's stern face nodding approval, the two figures walking side-by-side through a forest path (medium two-shot), Chandragupta drawing a wooden sword in a clearing and striking practice strokes, Chanakya watching from a tree shadow, Chandragupta gazing toward the horizon with resolve, Chanakya's hand resting on the boy's shoulder, fade to sunset over the canopy. Camera 4-15 feet, warm orange forest light, sparse jungle. Mood: foundational, patient, scheming." 60

post "hist_04_shivaji_aurangzeb_escape" "A 60-second mini-series: Shivaji's daring escape from Aurangzeb's court at Agra, smuggled out in baskets of sweets with his young son Sambhaji. Three characters: Shivaji, a Maratha warrior-king in his late 30s, neat black beard, jeweled turban, simple white robes; Aurangzeb, the Mughal emperor in his 50s, sharp aquiline nose, gray beard, ornate Mughal court robes, suspicious; and young Sambhaji, an eight-year-old prince in miniature Mughal-style noble attire. Beats: wide shot of Aurangzeb's marble court at Agra Fort, Aurangzeb seated on a low throne with suspicious narrow eyes, Shivaji kneeling on a marble floor in a formal salute, closeup of Shivaji's eyes calculating, young Sambhaji standing beside his father wide-eyed, Shivaji feigning fever and being moved to a guest chamber, closeup of large wicker baskets of sweets being filled, a guard inspecting one basket and waving it through (single guard shot), Shivaji curled inside a basket lid closing over him, the basket being carried on shoulders out of a courtyard, Sambhaji being carried out in a separate basket, the two emerging at night on horseback under torchlight outside the fort, Shivaji galloping into the darkness with Sambhaji clinging to his back. Camera 3-20 feet, Mughal palace warm gold tones shifting to torchlit night blues. Mood: cunning, tense, daring." 60

post "hist_05_lakshmibai_gwalior_laststand" "A 60-second mini-series: Rani Lakshmibai's final battlefield charge at Gwalior, 1858, sword in hand, her adopted son Damodar Rao tied to her back. Three characters: Rani Lakshmibai, a young queen in her late 20s, dressed in male warrior attire of saffron pagdi (turban) and chest armor, a sash across her chest, dark eyes fierce; her adopted son Damodar Rao, a six-year-old boy tied tightly to her back with a cloth sling; and her general Tantia Tope, a mustached Maratha commander in red turban beside her. Beats: wide shot of a smoke-filled battlefield near Gwalior fort at midday, Lakshmibai on a black warhorse rearing, closeup of her face fierce in the saffron pagdi, Damodar's small face wide-eyed peeking over her shoulder, Tantia Tope galloping past on his own horse sword raised, Lakshmibai swinging her sword against an unseen cavalryman (single-figure dynamic shot), sparks of steel-on-steel, a British cannon firing in the distance, Lakshmibai's horse leaping over a fallen banner, her sash flowing behind her, closeup of her hand gripping the reins tighter to secure Damodar, a final defiant cry with sword raised to the smoke-darkened sky, embers drifting around her silhouette, fade to dusk with the Indian flag silhouette behind. Camera 3-25 feet, harsh midday sun cutting through smoke, brass and saffron tones. Mood: fierce, sacrificial, immortal." 60

post "hist_06_ashoka_kalinga_remorse" "A 60-second mini-series: Emperor Ashoka walks the aftermath of the Kalinga battlefield and undergoes a moral awakening that turns him to Buddhism. Three characters: Ashoka, a powerful emperor in his late 30s, dark beard, royal Mauryan armor with gold accents, blood-spattered, sword still in hand; a dying soldier, a Kalinga warrior in torn leather armor, gray-faced, reaching out weakly; and a Buddhist monk in saffron robes, shaved head, calm presence, seated on a rock at the edge of the field. Beats: wide aerial-style shot of a battlefield covered with the dead and wounded at dusk, the Daya river running dark, Ashoka stepping past a fallen war elephant, closeup of his blood-spattered face, the dying soldier reaching a trembling hand toward him, closeup of the soldier's pleading eyes, Ashoka kneeling and looking at his own bloodied sword, the monk seated motionless on a rock watching, Ashoka rising and walking toward the monk slowly, monk's calm face under saffron hood, Ashoka dropping his sword into the mud (closeup of sword falling), Ashoka's hands covering his face, the monk extending a hand of peace, Ashoka opening his eyes changed, looking toward the orange horizon. Camera 4-30 feet, smoky red sunset, ash drifting. Mood: harrowing, redemptive, hushed." 60

post "hist_07_mirabai_krishna_bhakti" "A 60-second mini-series: the Rajput princess-poet Mirabai sings to her beloved Krishna idol in defiance of her royal family. Three characters: Mirabai, a slender woman in her 20s in saffron sari with ektara (one-string lute), barefoot, hair loose, eyes shining with bhakti; her husband Bhojraj, a young Rajput prince in royal robes with a confused tender expression watching from a doorway; and her mother-in-law Uda Bai, an older Rajput matriarch in heavy silks with a stern disapproving glare. Beats: wide shot of a Rajput palace courtyard at night lit by oil lamps, Mira in her saffron sari kneeling before a small Krishna idol on a low altar, closeup of the brass Krishna idol with a peacock feather, Mira plucking the ektara, her hair swinging as she begins to dance, Bhojraj in the doorway watching with quiet tenderness, Uda Bai's silhouette behind him with a hard expression, Mira spinning with arms outstretched, the flame of a diya lamp wavering, closeup of Mira's tear-streaked ecstatic face, the Krishna idol seeming to flicker into a faint smile in lamplight, Mira kneeling exhausted before the altar, fade to dawn light on the courtyard. Camera 3-12 feet, warm lamp-lit interior, saffron and gold palette. Mood: ecstatic, devotional, defiant." 60

post "hist_08_akbar_birbal_court" "A 60-second mini-series: a classic Akbar-Birbal scene where Birbal's wit defuses an impossible courtly demand. Three characters: Akbar, the Mughal emperor in his 40s with a neat short beard, jeweled turban, ornate court robes, amused intelligent eyes; Birbal, his chief advisor and jester in colorful Mughal courtier attire, twinkling mischievous eyes, beard slightly grayer; and a merchant plaintiff, a portly older man in plain cotton kurta, animated and agitated, holding a small cloth bag. Beats: wide shot of the Diwan-i-Khas at Fatehpur Sikri, Akbar seated on his white marble throne, Birbal standing slightly to the side smirking, the merchant plaintiff prostrating himself, closeup of the merchant's animated face arguing, Akbar raising one eyebrow toward Birbal, Birbal stepping forward with hands folded and a knowing smile, closeup of Birbal whispering at Akbar's ear, the merchant placing his cloth bag on a balance scale (closeup of brass scale), Birbal placing a single stone on the other side that tips it perfectly, Akbar bursting into a hearty laugh, the merchant's confused face turning into a relieved bow, Birbal's playful sideways wink. Camera 3-15 feet, warm tungsten-and-amber palace light, polished marble reflections. Mood: clever, warm, court-elegant." 60

post "hist_09_bhagat_singh_courtroom" "A 60-second mini-series: Bhagat Singh's defiant moment in a British colonial courtroom during the Lahore Conspiracy Case trial. Three characters: Bhagat Singh, a young revolutionary in his early 20s, signature thin mustache and felt hat, white shirt with rolled sleeves, calm defiant eyes; Sukhdev Thapar, his fellow revolutionary in his 20s, dark mustache, simple kurta, equally calm; and a British colonel-judge in his 50s, in a pith helmet and khaki colonial uniform with brass insignia, stern reddened face. Beats: wide shot of a wood-paneled colonial courtroom with British flag, Bhagat Singh standing tall in the wooden dock his felt hat in hand, closeup of his calm defiant face, Sukhdev beside him with steady unblinking eyes, the colonel-judge banging a heavy wooden gavel, closeup of the gavel striking, Bhagat Singh stepping forward and raising a clenched fist, his lips silently mouthing 'Inquilab Zindabad,' closeup of his fist clenched at chest height, the colonel's reddened furious face, two colonial guards stiffening at the back of the room, Sukhdev's slight approving nod, Bhagat Singh's gaze turning slowly toward the camera unflinching, fade to a single shaft of dust-lit window light on his face. Camera 2-15 feet, harsh courtroom daylight, brown wood and khaki tones. Mood: defiant, immortal, electric." 60

post "hist_10_shankaracharya_mandana_debate" "A 60-second mini-series: Adi Shankaracharya debates the scholar Mandana Mishra at his home in Mahishmati, with Mandana's wife Ubhaya Bharati as the impartial judge. Three characters: Adi Shankaracharya, a young saint in his 20s, shaved head with topknot, simple saffron robes, intense luminous eyes; Mandana Mishra, an elder Vedic scholar in his 50s, long gray beard, white dhoti and angavastram, sacred thread across chest, scholarly and proud; and Ubhaya Bharati, Mandana's wife, an elegant woman in her 40s in a deep red sari with gold jari border, intelligent presiding face. Beats: wide shot of a sun-dappled courtyard with a banyan tree and white-pillared veranda, Shankaracharya entering through a flowered gate in saffron robes, Mandana receiving him with a formal bow at the threshold, the two seated cross-legged on opposite woven mats, Ubhaya Bharati seated on a slight raised platform between them holding two fresh flower garlands (closeup of the garlands), Ubhaya Bharati placing one garland around each of their necks (single-figure shot each), Shankara raising one hand in argument expression intense, Mandana counter-arguing with raised forefinger, closeup of Mandana's garland visibly beginning to wilt, Shankara's garland still fresh and bright, Mandana lowering his head in graceful acknowledgement, Ubhaya Bharati's gentle final nod of judgment. Camera 3-12 feet, dappled golden afternoon light, deep saffron and white palette. Mood: scholarly, profound, civil." 60

post "hist_11_eklavya_drona_thumb" "A 60-second mini-series from the Mahabharata: the tribal archer Eklavya offers his right thumb as guru-dakshina to Drona, after secretly mastering archery from a clay statue. Three characters: Eklavya, a tribal boy of about 16 in simple deerskin and leaves, lean build, dark skin, calm dignified face, a homemade bow at his side; Dronacharya, the royal archery teacher in his 50s, white beard, simple Brahmin attire with sacred thread, severe expression; and prince Arjuna, a young Pandava prince in his late teens in simple but fine cloth, golden armband, tense observer. Beats: wide shot of a dense forest clearing with morning mist, Eklavya kneeling before a roughly-made clay statue of Drona placed on a small earthen mound, Eklavya practicing archery, closeup of his arrow striking dead center, Drona arriving at the edge of the clearing with Arjuna at his shoulder, closeup of Drona's stunned face seeing the statue, Arjuna's tense observation, Eklavya rising and bowing reverently to Drona, Drona's stern voice asking for guru-dakshina (single-figure shot of Drona speaking), closeup of Eklavya's calm acceptance, Eklavya drawing a small knife, an extreme tasteful closeup of the hand and knife (no graphic detail, just the gesture), a single drop falling onto a leaf, Eklavya offering his severed thumb palm-up to Drona, Drona's frozen face, Arjuna lowering his gaze, Eklavya's serene final smile. Camera 3-15 feet, soft forest morning light, green and earth tones. Mood: heart-rending, sublime, sacrificial." 60

post "hist_12_tulsidas_ramcharitmanas_ghats" "A 60-second mini-series: the poet-saint Tulsidas writes the Ramcharitmanas at the ghats of Varanasi, with a mysterious devotee (a hidden form of Hanuman) listening beside him. Two characters: Tulsidas, an old saint in his 60s, white beard and long hair, simple white dhoti, sacred tilak on forehead, a palm-leaf manuscript on his lap and a reed pen; and a mysterious devotee in saffron, a strong-built man with calm intent eyes (subtly Hanuman in mortal form), seated beside him. Beats: wide shot of Varanasi's Manikarnika ghat at dawn with the Ganges flowing and oil lamps floating, Tulsidas seated cross-legged on a stone platform with palm leaves before him, closeup of his ink-pot and reed pen, the saffron-robed devotee approaching from behind and sitting at a respectful distance, closeup of Tulsidas reciting a verse with eyes closed, the devotee's calm face listening with subtle joy, Tulsidas dipping the pen and inscribing a palm leaf (closeup of the script being formed), the Ganges glittering in the rising sun, closeup of the devotee's hand silently keeping rhythm against his knee, a single tear sliding down Tulsidas's cheek, Tulsidas turning to look but the devotee is gone, only a faint footprint of a paw-like form on the stone (subtle Hanuman hint), Tulsidas's smile of understanding, the manuscript title 'Sri Ramcharitmanas' being inscribed on the first palm leaf. Camera 3-20 feet, warm Banaras dawn gold-and-saffron palette, mist over the river. Mood: devotional, eternal, hushed." 60

echo
echo "=== All 12 historical/mythological mini-series submitted ==="
echo "Status:  curl -s $BACKEND/api/projects | python3 -m json.tool | head -200"
echo "Queue scanner will drain these FIFO behind the current ad backlog."
